name: Check for changes since last success
description: Check if there are changes since the last successful commit in a working directory.

inputs:
  working-directory:
    description: 'The working directory to check for changes.'
    required: true
    default: '.'
  github-token:
    description: 'GitHub token to use for authentication.'
    required: false
    default: '${{ github.token }}'
outputs:
  success-commit:
    description: 'The commit SHA of the last successful run.'
    value: ${{ steps.changes.outputs.success_commit }}
  has-changes:
    description: 'Whether there are changes since the last successful run.'
    value: ${{ steps.changes.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    # Get the last successful run for the current workflow on the current branch
    - id: changes
      shell: bash
      run: |
        # Get the last successful run for the current workflow
        branch_name=$(git rev-parse --abbrev-ref HEAD)
        # echo "Branch name: $branch_name"
        # gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1
        # gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1 --json status,conclusion,headSha
        success_commit=$(gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1 --json databaseId,status,conclusion,headSha -q '.[] | select(.databaseId != null) | .headSha')
        echo "success_commit: $success_commit"
        echo "success_commit=$success_commit" >> "$GITHUB_OUTPUT"
        has_changes=$(git diff --quiet $success_commit ${{ inputs.working-directory }} || echo true)

        # if [ "$has_changes" = "true" ]; then
        #   echo "Changes detected since last successful run."
        #   echo "changes=true" >> "$GITHUB_OUTPUT"
        # else
        #   echo "No changes since last successful run."
        #   echo "changes=false" >> "$GITHUB_OUTPUT"
        # fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
