name: Check for changes since last success
description: Check if there are changes since the last successful commit in a working directory.

inputs:
  working-directory:
    description: 'The working directory to check for changes.'
    required: true
    default: '.'
  github-token:
    description: 'GitHub token to use for authentication.'
    required: false
    default: '${{ github.token }}'

runs:
  using: 'composite'
  steps:
    - name: Find commit SHA of last successful run
      id: last-successful-run
      shell: bash
      run: |
        # Get the last successful run for the current workflow
        gh run list --workflow ${{ github.workflow }} --status success --limit 1 --json status,databaseId,headSha
        last_successful_run=$(gh run list --workflow ${{ github.workflow }} --status success --limit 1 --json status,databaseId,headSha -q '.[] | select(.databaseId != null) | .headSha')

        # Check if a successful run was found
        if [ -z "$last_successful_run" ]; then
          echo "No successful runs found."
          exit 1
        fi

        echo "Last successful run SHA: $last_successful_run"
        exit 1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
