name: Check for changes since last success
description: Check if there are changes since the last successful commit in a working directory.

inputs:
  working-directory:
    description: 'The working directory to check for changes.'
    required: true
    default: '.'
  github-token:
    description: 'GitHub token to use for authentication.'
    required: false
    default: '${{ github.token }}'
outputs:
  commit:
    description: 'The commit SHA of the last successful run.'
    value: ${{ steps.last-successful-run.outputs.commit }}
  changes:
    description: 'Whether there are changes since the last successful run.'
    value: ${{ steps.check-changes.outputs.changes }}

runs:
  using: 'composite'
  steps:
    # Get the last successful run for the current workflow on the current branch
    - id: last-successful-run
      shell: bash
      run: |
        # Get the last successful run for the current workflow
        branch_name=$(git rev-parse --abbrev-ref HEAD)
        # echo "Branch name: $branch_name"
        # gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1
        # gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1 --json status,conclusion,headSha
        last_successful_run=$(gh run list --workflow ${{ github.workflow }} --branch "$branch_name" --status success --limit 1 --json databaseId,status,conclusion,headSha -q '.[] | select(.databaseId != null) | .headSha')
        echo "last_successful_run: $last_successful_run"
        echo "commit=$last_successful_run" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}

    # Check if there are changes in the working directory since the last successful run
    - id: check-changes
      shell: bash
      run: |
        # Check if there are changes in the working directory since the last successful run
        git diff ${{ steps.last-successful-run.outputs.commit }} -- ${{ inputs.working-directory }}
        git diff --quiet ${{ steps.last-successful-run.outputs.commit }} -- ${{ inputs.working-directory }}
        if [ $? -eq 0 ]; then
          echo "No changes since last successful run."
          echo "changes=false" >> "$GITHUB_OUTPUT"
        else
          echo "Changes detected since last successful run."
          echo "changes=true" >> "$GITHUB_OUTPUT"
        fi
