name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to create a comment (actions/github-script)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: kt-actions/npm-ci-check@v1
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(vars.MATRIX_NODE_VERSION) }}
    steps:
      - uses: kt-actions/npm-ci-test@v1
        with:
          # pass the matrix node version to the called workflow
          node-version: ${{ matrix.node-version }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}

  sonar:
    runs-on: ubuntu-latest
    steps:
      - id: do-sonar
        run: |
          if [[ -z "${{ secrets.SONAR_TOKENX }}" ]]; then
            echo "sonar-token is not set"
            echo "result=false" >> "$GITHUB_OUTPUT"
          else
            echo "sonar-token is set"
            echo "result=true" >> "$GITHUB_OUTPUT"
          fi

      - uses: kt-actions/npm-ci-sonar@v1
        if: steps.do-sonar.outputs.result == 'true'
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}

  # ci:
  #   uses: kt-workflows/npm-ci/.github/workflows/main.yml@v1
  #   with:
  #     # pass the matrix node version to the called workflow
  #     matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
  #     check-script: ''
  #     test-script: ''
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
