name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup-node
        uses: kt-actions/setup-node-minmax@v1
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./**/package-lock.json

      - run: echo "setup-node-version = ${{ steps.setup-node.node-version }}"

      - id: npm-cache
        uses: actions/cache@v4
        with:
          path: ./**/node_modules
          key: ${{ runner.os }}-npm-${{ steps.setup-node.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - run: npm run lint

      - run: npm run check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(vars.MATRIX_NODE_VERSION) }}
    steps:
      - uses: actions/checkout@v4

      - id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./**/package-lock.json

      - run: echo "setup-node-version = ${{ steps.setup-node.node-version }}"

      - id: npm-cache
        uses: actions/cache@v4
        with:
          path: ./**/node_modules
          key: ${{ runner.os }}-npm-${{ steps.setup-node.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - run: npm run build

      - run: npm run test
  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      # required for all workflows
      security-events: write
      # required to fetch internal or private CodeQL packs
      packages: read
      # only required for workflows in private repositories
      actions: read
      contents: read
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup-node
        uses: kt-actions/setup-node-minmax@v1
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./**/package-lock.json

      - id: npm-cache
        uses: actions/cache@v4
        with:
          path: ./**/node_modules
          key: ${{ runner.os }}-npm-${{ steps.setup-node.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - run: npm run build

      - run: npm run coverage

      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
