name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to delete cache (actions/cache)

env:
  # set the default node version to use in the matrix
  DEFAULT_MATRIX_NODE_VERSION: '[20, 22]'
  # DEFAULT_CACHE_ADDITIONAL_PATH: 'node_modules/.cache'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(github) }}
        shell: cat {0}

  config:
    runs-on: ubuntu-latest
    outputs:
      sonar: ${{ steps.sonar.outputs.sonar }}
      cache-additional-path: ${{ steps.cache-additional-path.outputs.cache-additional-path }}
    steps:
      - id: sonar
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN is not set, skipping sonar job"
            echo "sonar=false" >> "$GITHUB_OUTPUT"
          else
            echo "SONAR_TOKEN is set, running sonar job"
            echo "sonar=true" >> "$GITHUB_OUTPUT"
          fi

      - id: cache-additional-path
        run: |
          # set the cache additional path to use
          if [ -z "${{ vars.CACHE_ADDITIONAL_PATH }}" ]; then
            echo "CACHE_ADDITIONAL_PATH is not set, using default"
            # use the default cache additional path
            echo "cache-additional-path=${{ env.DEFAULT_CACHE_ADDITIONAL_PATH }}" >> "$GITHUB_OUTPUT"
          else
            # use the cache additional path
            echo "CACHE_ADDITIONAL_PATH is set, using cache additional path"
            echo "cache-additional-path=${{ vars.CACHE_ADDITIONAL_PATH }}" >> "$GITHUB_OUTPUT"
          fi

  ci-subpackage:
    runs-on: ubuntu-latest
    steps:
      - id: check-changes
        uses: kt-workflows/actions/has-changes-since-last-success@main
        with:
          paths: |
            subpackage
            .githooks

      - uses: actions/checkout@v6
        if: steps.check-changes.outputs.has-changes == 'true'

      - run: subpackage/test.sh
        shell: bash
        if: steps.check-changes.outputs.has-changes == 'true'

  check:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-check@main
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache-additional-path: needs.config.outputs.cache-additional-path
          # cache-reset: true

  test:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(vars.MATRIX_NODE_VERSION) }}
    steps:
      - uses: kt-workflows/actions/npm-ci-test@main
        with:
          # pass the matrix node version to the called workflow
          node-version: ${{ matrix.node-version }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          # cache-reset: true

  sonar:
    if: needs.config.outputs.sonar == 'true'
    needs: config
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-sonar@main
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          fail-on-empty-token: true
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          # cache-reset: true

  required-main:
    name: required-main
    if: always()
    needs:
      - ci-subpackage
      - check
      - test
      - sonar
    runs-on: ubuntu-latest
    steps:
      - name: Verify required jobs for main
        shell: bash
        run: |
          [[ "${{ needs['ci-subpackage'].result }}" == "success" ]] || exit 1
          [[ "${{ needs.check.result }}" == "success" ]] || exit 1
          [[ "${{ needs.test.result }}" == "success" ]] || exit 1
          [[ "${{ needs.sonar.result }}" == "success" ]] || exit 1

  required-contribution:
    name: required-contribution
    if: always()
    needs:
      - ci-subpackage
      - check
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Verify required jobs for contribution
        shell: bash
        run: |
          [[ "${{ needs['ci-subpackage'].result }}" == "success" ]] || exit 1
          [[ "${{ needs.check.result }}" == "success" ]] || exit 1
          [[ "${{ needs.test.result }}" == "success" ]] || exit 1
