name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to delete cache (actions/cache)

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(github) }}
        shell: cat {0}
  ci-subpackage:
    runs-on: ubuntu-latest
    steps:
      - id: check-changes
        uses: kt-actions/has-changes-since-last-success@v1
        with:
          paths: |
            subpackage
            .githooks

      - uses: actions/checkout@v4
        if: steps.check-changes.outputs.has-changes == 'true'

      - run: subpackage/test.sh
        shell: bash
        if: steps.check-changes.outputs.has-changes == 'true'

  check:
    # if: true == false
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-check@main
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          # cache-reset: true

  test:
    # if: true == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(vars.MATRIX_NODE_VERSION) }}
    steps:
      - uses: kt-workflows/actions/npm-ci-test@main
        with:
          # pass the matrix node version to the called workflow
          node-version: ${{ matrix.node-version }}
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          # cache-reset: true

  sonar:
    # if: true == false
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-sonar@main
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          fail-on-empty-token: true
          cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
          # cache-reset: true
