name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to delete cache (actions/cache)

env:
  # set the default node version to use in the matrix
  DEFAULT_MATRIX_NODE_VERSION: '[22, 24]'
  DEFAULT_CACHE_RESET: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(github) }}
        shell: cat {0}

  config:
    runs-on: ubuntu-latest
    outputs:
      matrix-node-version: ${{ steps.matrix-node-version.outputs.matrix-node-version }}
      sonar: ${{ steps.sonar.outputs.sonar }}
      cache-reset: ${{ steps.cache-reset.outputs.cache-reset }}
    steps:
      - id: matrix-node-version
        run: |
          # Set the node version to use in the matrix
          echo "matrix-node-version=${{ vars.MATRIX_NODE_VERSION || env.DEFAULT_MATRIX_NODE_VERSION || '' }}" >> "$GITHUB_OUTPUT"

      - id: sonar
        run: |
          # Check if the SONAR_TOKEN secret is set, if not skip the sonar job
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN is not set, skipping sonar job"
            echo "sonar=false" >> "$GITHUB_OUTPUT"
          else
            echo "SONAR_TOKEN is set, running sonar job"
            echo "sonar=true" >> "$GITHUB_OUTPUT"
          fi

      - id: cache-reset
        run: |
          # Set the cache reset to use
          echo "cache-reset=${{ vars.CACHE_RESET || env.DEFAULT_CACHE_RESET }}" >> "$GITHUB_OUTPUT"

  ci-subpackage:
    runs-on: ubuntu-latest
    steps:
      - id: check-changes
        uses: kt-workflows/actions/has-changes-since-last-success@main
        with:
          paths: |
            subpackage
            .githooks

      - uses: actions/checkout@v6
        if: steps.check-changes.outputs.has-changes == 'true'

      - run: subpackage/test.sh
        shell: bash
        if: steps.check-changes.outputs.has-changes == 'true'

  check:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-check@main
        with:
          matrix-node-version: ${{ needs.config.outputs.matrix-node-version }}
          cache-reset: ${{ needs.config.outputs.cache-reset }}

  test:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.config.outputs.matrix-node-version) }}
    steps:
      - uses: kt-workflows/actions/npm-ci-test@main
        with:
          node-version: ${{ matrix.node-version }}
          cache-reset: ${{ needs.config.outputs.cache-reset }}

  sonar:
    needs: config
    if: needs.config.outputs.sonar == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/npm-ci-sonar@main
        with:
          matrix-node-version: ${{ needs.config.outputs.matrix-node-version }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          fail-on-empty-token: true
          cache-reset: ${{ needs.config.outputs.cache-reset }}

  required-main:
    name: required-main
    needs:
      - ci-subpackage
      - check
      - test
      - sonar
    runs-on: ubuntu-latest
    steps:
      - name: Verify required jobs for main
        shell: bash
        run: |
          echo "Required jobs for main are fulfilled"

  required-contribution:
    name: required-contribution
    needs:
      - ci-subpackage
      - check
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Verify required jobs for contribution
        shell: bash
        run: |
          echo "Required jobs for contribution are fulfilled"
